<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\drupal_rating\Services\RatingService;

/**
 * @file
 * Rating Module .
 */
function drupal_rating_theme($existing, $type, $theme, $path) {
  return [
    'block-rating' => [
      'variables' => ['data' => NULL],
    ],
  ];
}

function drupal_rating_entity_delete(EntityInterface $entity) {
  $RatingService = new RatingService(\Drupal::service('database'), \Drupal::configFactory());
  $RatingService->deleteNodeRating($entity->id());

}
